Imports System.Threading
Public Class frmMatches

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        TblMatchesTableAdapter1.Fill(DbCSGLDataSet1.tblMatches)
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub GridControl1_DoubleClick(sender As Object, e As EventArgs) Handles GridControl1.DoubleClick
        Dim CSGLItem As New CSGLItem
        CSGLItem.name = "ty"
    End Sub

    Private Sub frmMatches_Disposed(sender As Object, e As EventArgs) Handles Me.Disposed
        frmMain.WindowState = FormWindowState.Normal
    End Sub

    Private Sub frmMatches_FormClosing(sender As Object, e As FormClosingEventArgs) Handles Me.FormClosing
        TblMatchesTableAdapter1.Update(DbCSGLDataSet1)
    End Sub

    Private Sub frmMatches_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.WindowState = FormWindowState.Normal
        frmMain.WindowState = FormWindowState.Minimized
    End Sub

    Private Sub BarButtonItem2_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem2.ItemClick
        
    End Sub
End Class
