Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Columns
Imports System.Threading
Public Class frmMatches

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        TblMatchesTableAdapter1.Fill(DbCSGLDataSet1.tblMatches)
        gviewMatches.ShowLoadingPanel()
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub GridControl1_DoubleClick(sender As Object, e As EventArgs) Handles GridControl1.DoubleClick
        Dim CSGLItem As New CSGLItem
        CSGLItem.name = "ty"
    End Sub

    Private Sub frmMatches_Disposed(sender As Object, e As EventArgs) Handles Me.Disposed
        frmMain.WindowState = FormWindowState.Normal
    End Sub

    Private Sub frmMatches_FormClosing(sender As Object, e As FormClosingEventArgs) Handles Me.FormClosing
        TblMatchesTableAdapter1.Update(DbCSGLDataSet1)
    End Sub

    Private Sub frmMatches_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.WindowState = FormWindowState.Normal
        frmMain.WindowState = FormWindowState.Minimized
        gviewMatches.HideLoadingPanel()
    End Sub

    Private Sub BarButtonItem2_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem2.ItemClick

    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        gviewMatches.ShowFilterEditor(gviewMatches.Columns("Team 1"))
    End Sub

    Private Sub mnuClearFilter_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuClearFilter.ItemClick
        If MsgBox("Are you sure?", MsgBoxStyle.YesNo, "Clear All Filters") = MsgBoxResult.Yes Then
            gviewMatches.ClearColumnsFilter()
        End If

    End Sub

    Private Sub mnuDateRange_EditValueChanged(sender As Object, e As EventArgs) Handles mnuDateRange.EditValueChanged
      

    End Sub

    Private Sub mnuDateRange_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuDateRange.ItemClick

    End Sub

    Public Sub FilterColumn(ByVal column As String, ByVal filtervalue As String)
        If Not String.IsNullOrWhiteSpace(filtervalue) And Not (InStr(filtervalue, "1/1/0001") = -1) Then
            'Dim view As ColumnView = gviewMatches
            column = column.Replace(" ", String.Empty)
            gviewMatches.Columns(column).FilterInfo = New ColumnFilterInfo(String.Format("[{0}]='{1}'", column, filtervalue.Trim))
            'view.ActiveFilter.Add(view.Columns(column), New ColumnFilterInfo(String.Format("[{0}]='{1}'", column, filtervalue), ""))
            LogMe(String.Format(colMatchDate.FilterInfo.DisplayText))
        End If

    End Sub

    Private Sub mnuFilterBest1_CheckedChanged(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuFilterBest1.CheckedChanged
        FilterColumn("BestOf", "1")
        mnuFilterBest2.Checked = False
        mnuFilterBest3.Checked = False
    End Sub

    Private Sub mnuFilterBest2_CheckedChanged(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuFilterBest2.CheckedChanged
        FilterColumn("BestOf", "2")
        mnuFilterBest1.Checked = False
        mnuFilterBest3.Checked = False
    End Sub

    Private Sub mnuFilterBest3_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuFilterBest3.ItemClick
        FilterColumn("BestOf", "3")
        mnuFilterBest2.Checked = False
        mnuFilterBest1.Checked = False
    End Sub

    Private Sub BarLargeButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarLargeButtonItem1.ItemClick
        gviewMatches.ShowCustomFilterDialog(colMatchDate)
    End Sub

    Private Sub ShowFind_CheckedChanged(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuCheckShowFind.CheckedChanged
        If mnuCheckShowFind.Checked = True Then gviewMatches.ShowFindPanel()
        If mnuCheckShowFind.Checked = False Then gviewMatches.HideFindPanel()
    End Sub


End Class
